name: PiggyBack
version: 2.4
main: me.blubdalegend.piggyback.Piggyback
api-version: 1.16
softdepend: [Citizens, PlaceholderAPI, MVdWPlaceholderAPI, WorldGuard]
authors: [DrkMatr1984, BlubDaLegend]
description: Crouch, Click, Piggyback!

permissions:
    piggyback.use:
        description: Allows the user to pick up/ride entities and players, providing the player being picked up/ridden is not toggled off
        default: true
    piggyback.toggle:
        description: Allows the user to toggle on/off their ability to be picked up/ridden
        default: op
    piggyback.toggle.other:
        description: Allows the user to toggle on/off other users' ability to be picked up/ridden
        default: op
    piggyback.messages:
        description: Allows the user to toggle on/off piggyback messages for themselves
        default: op
    piggyback.messages.other:
        description: Allows the user to toggle on/off piggyback messages for others
        default: op
    piggyback.cooldown.bypass:
        description: Bypass the pickup cooldown
        default: op
    piggyback.reload:
        description: Reload Piggyback config and language file
        default: op