name: PiggyBack
version: 1.9.9
main: me.blubdalegend.piggyback.Piggyback
softdepend: [Citizens]
authors: [DrkMatr1984, BlubDaLegend]
description: Crouch, Click, Piggyback!
commands:
    pback:
        description: Main Piggyback command, also displays help
        aliases: [piggyback, piggyb, pb]
    pback help:
        description: Displays the help page
    pback toggle:
        description: Toggle your ability to be picked up
    pback messages:
        description: Toggle Piggyback messages
permissions:
    piggyback.use:
        description: Allows the user to pick up entities and players, providing the player being picked up is not toggled off
        default: true
    piggyback.help:
        description: Allows the user to view the /pback help
        default: true
    piggyback.toggle:
        description: Allows the user to toggle on/off their ability to be picked up
        default: op
    piggyback.messages:
        description: Allows the user to toggle on/off piggyback messages for themselves
        default: op
    piggyback.cooldown.bypass:
        description: Bypass the pickup cooldown
        default: op